name: Build alpine kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install qemu-user-static
      - uses: docker://arm32v6/alpine:edge
        with:
          entrypoint: ''
          args: |
            sh -c "
            apk add alpine-sdk \
            && cd alpine-kernel \
            && abuild checksum \
            && abuild -r
            "
      - run: tree && ls -al
