name: Build alpine kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install qemu-user-static
      - uses: docker://arm32v6/alpine:edge
        with:
          entrypoint: ''
          args: |
            sh -c "
               apk add alpine-sdk sudo \
            && adduser builder
            && addgroup builder abuild
            && echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
            && chmod 440 /etc/sudoers.d/takesako
            && chown builder:abuild alpine-kernel \
            && mkdir -p /var/cache/distfiles
            && chgrp abuild /var/cache/distfiles
            && chmod g+w /var/cache/distfiles
            && cd alpine-kernel \
            && su builder -c "
               abuild checksum \
            && abuild -r
            ""
      - run: tree && ls -al
