name: Build kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install git bc bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-armhf 
      - run: git clone --depth=1 https://github.com/raspberrypi/linux
      - run: |
          cd linux
          curl -L https://github.com/doronz88/pymobiledevice3/files/13638682/idevice_debug_ncm.patch | patch -p1
          make bcmrpi_defconfig
          ./scripts/config --set-val USB_IDEVICE_DEBUG_NCM m
          cat .config | grep USB_IDEVICE_DEBUG_NCM
          make -j6 zImage modules dtbs
          make clean
        env: 
          KERNEL: kernel
          LOCALVERSION: -dev
          ARCH: arm
          CROSS_COMPILE: arm-linux-gnueabihf-
      - run: |
          mkdir -p boot/overlays
          cp arch/arm/boot/zImage boot/kernel.img
          cp arch/arm/boot/dts/broadcom/*.dtb boot/
          cp arch/arm/boot/dts/overlays/*.dtb* boot/overlays/
      - run: cp linux/install.sh boot/ && chmod 755 boot/install.sh
      - run: tar -cf - ./boot | zstd --ultra -22 -T0 > boot.tar.zst
      - run: gh release create linux boot.tar.zst
        env: 
          GH_TOKEN: ${{ github.token }}
