name: Build lib
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt install -y qemu-user-static
      - uses: ./build_lib
        with:
          entrypoint: ''
          args: bash -c "mkdir bin_s && mv /output/* ./"
      - run: cd bin_s && tar -cf - * | zstd --ultra -22 > ../bin_s.tar.zst
      - run: gh release create bin_s bin_s.tar.zst
        env: 
          GH_TOKEN: ${{ github.token }}
