name: Build kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo sed -i s/jammy/noble/g /etc/apt/sources.list
      - run: sudo apt update && sudo apt install git bc bison flex libssl-dev make libc6-dev libncurses5-dev clang llvm lld crossbuild-essential-arm64 
      - run: git clone --depth=1 https://github.com/raspberrypi/linux
      - run: |
          cd linux
          curl -L https://github.com/doronz88/pymobiledevice3/files/13638682/idevice_debug_ncm.patch | patch -p1
          curl -L https://github.com/zen-kernel/zen-kernel/releases/download/v6.6.13-lqx1/v6.6.13-lqx1.patch.xz | xzcat | patch -p1
          make bcm2711_defconfig
          ./scripts/config --set-val USB_IDEVICE_DEBUG_NCM m
          ./scripts/config --set-val CONFIG_LTO_CLANG_THIN y
          ./scripts/config --set-val CONFIG_MODULE_COMPRESS_ZSTD y
          ./scripts/config --set-val CONFIG_ZSWAP_DEFAULT_ON y
          ./scripts/config --set-val CONFIG_ZSTD_COMPRESS y
          ./scripts/config --set-val CONFIG_ZSTD_DECOMPRESS y
          cat .config | grep USB_IDEVICE_DEBUG_NCM
          make -j6 Image.zst modules dtbs
        env: 
          KERNEL: kernel8
          LOCALVERSION: -dev
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
          KCFLAGS: -pipe -O2 -march=armv8-a+fp+simd
          LLVM: 1

      - run: cp kernel/install.sh linux/ && chmod 755 linux/install.sh
      - run: tar -cf - ./linux | zstd --ultra -22 -T0 > linux.tar.zst
      - run: gh release create linux-arm64 linux.tar.zst
        env: 
          GH_TOKEN: ${{ github.token }}
