name: Build netmuxd
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install qemu-user-static
      - uses: ./netmuxd
        with:
          entrypoint: ''
          args: sh -c 'mv /output/netmuxd ./'
      - run: gh release create netmuxd ${{ github.workspace }}/netmuxd
        env: 
          GH_TOKEN: ${{ github.token }}
