name: Build netmuxd cross
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "deb [arch=armhf] http://archive.raspbian.org/raspbian bullseye main contrib non-free" | sudo tee -a /etc/apt/sources.list
          wget https://archive.raspbian.org/raspbian.public.key -O - | sudo apt-key add -
          sudo dpkg --add-architecture armhf
      - run: sudo apt update || sh -c "exit $(($? == 100 ? 0 : $?))"
      - run: sudo apt install crossbuild-essential-armhf libtool-bin:armhf libavahi-glib-dev:armhf libavahi-client-dev:armhf libusb-1.0-0-dev:armhf libssl-dev:armhf libplist++-dev:armhf
      - run: |
          git clone --recursive https://github.com/jkcoxson/netmuxd.git
          git clone --recursive https://github.com/zeyugao/zeroconf-rs.git
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup target add arm-unknown-linux-gnueabihf
          cd netmuxd
          cargo build --target=arm-unknown-linux-gnueabihf --release --bin netmuxd
      - run: gh release create netmuxd_cross netmuxd/target/arm-unknown-linux-gnueabihf/release/netmuxd
        env: 
          GH_TOKEN: ${{ github.token }}
