name: Build netmuxd
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install qemu-user-static
      - uses: ./netmuxd
        with:
          entrypoint: ''
          args: mv /output/netmuxd /github/workspace/netmuxd-bin
      - run: zstd --ultra -22 -T0 netmuxd-bin
      - run: gh release create netmuxd netmuxd-bin.zst
        env: 
          GH_TOKEN: ${{ github.token }}
