name: Build netmuxd
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install qemu-user-static
      - uses: ./netmuxd
      - run: gh release create netmuxd ${{ github.workspace }}/target/release/netmuxd
        env: 
          GH_TOKEN: ${{ github.token }}
