name: Build wheel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install qemu-user-static
      - uses: ./wheel
        with:
          entrypoint: ''
          args: mkdir /github/workspace/wheel/ && mv /output/wheel/* /github/workspace/wheel/
      - run: tar -cf - wheel | zstd --ultra -22 -T0 > wheel.tar.zst
      - run: gh release create wheel wheel.tar.zst
        env: 
          GH_TOKEN: ${{ github.token }}
