name: Build altserver
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install qemu-user-static
      - uses: ./altserver
        with:
          entrypoint: ''
          args: sh -c 'mv /output/altserver /github/workspace'
      - run: zstd --ultra -22 altserver
      - run: gh release create altserver altserver.zst
        env: 
          GH_TOKEN: ${{ github.token }}
