name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          entrypoint: ''
          args: bash -c "pwd && whoami && ls -al && df -alh"
